### ISSUE TITLE
sendResponse from getMessage API

### ISSUE THREAD

**Issue by YanivSilberman** [extend-chrome/messages#3]
First and foremost, this project is amazing and a real lifesaver for my app. 

I'm trying to await a response from the getMessage API but can't seem to find a way to do it. Using the messages API I can, but I'm unsure how to use typescript to guard the payload with it. How can I leverage the ability to send a response, while also leveraging the ability to type check payloads?

For example:

```ts
import { getMessage } from '@extend-chrome/messages';

interface Payload {
  arg: 1;
}

export const [sendReady, readyStream, waitForReady] = getMessage<Payload>('READY');

// background
sendReady.then((response) => console.log(response)); // { ping: true }

// content
readyStream.subscribe(([{ arg }, sender], sendResponse)) => {
  sendResponse({ ping: true }); 

  OR

  return { ping: true };
});

```

Thank you!

**Comment by jacksteamdev** [comment]
@YanivSilberman Great question! To use a message response, pass a second type and an options object.

```typescript
import { getMessage } from "@extend-chrome/messages";

interface Payload { arg: 1 }
interface ResponsePayload { ping: boolean }

export const [
  sendReady,
  readyStream,
  waitForReady, // this guards 👇 the response
] = getMessage<Payload, ResponsePayload>(
  "READY",
  { async: true } // 👈 this tells it to listen for a response
);

// background
sendReady.then((response) => console.log(response)); // { ping: true }

// content
readyStream.subscribe(
  // The args array will have 👇 a sendResponse function now
  ([{ arg }, sender, sendResponse]) => {
    sendResponse({ ping: true }); // call sendResponse to respond
  }
);
```

I'm so excited to hear that you are using this project! I personally can't imagine using Chrome extension messages without it. 😉

Check out [`rollup-plugin-chrome-extension`](https://github.com/extend-chrome/rollup-plugin-chrome-extension#rollup-plugin-chrome-extension) if you get a chance. It saves me a lot of time as well.

**Comment by YanivSilberman** [comment]
Wow thanks for the prompt and detailed response! that's exactly what I needed. Cheers

**Comment by YanivSilberman** [comment]
Is there a way to `sendResponse` in `subscribe` after an async request? I'm getting `Error: chrome.runtime.lastError is undefined` from 
```ts 
apiQueryStream.subscribe(async ([{ query, variables, options }, _, sendResponse]) => {
    const response = await api.query({
      query,
      variables,
      ...options
    });

    sendResponse(response);
 });
```

**Comment by jacksteamdev** [comment]
That looks ok to me... Are you getting the error from inside the subscribe callback, or on the other side as a rejection from the sendMessage call?

It's hard to know what is happening without a minimum reproduction. I would definitely add a catch to that api.query() call. Maybe it's throwing.

Check the error object. It should have `coreResponse` and `coreMessage` properties that might shed some light.

**Comment by YanivSilberman** [comment]
Oh right, I'm calling `await sendApiQuery` in my content script, the stream is in the background script. Stream works perfectly fine, the API call returns the right data. In fact, if I sendResponse without awaiting, it works well. The error is on the content script, only when I await an async call.

```ts
// content 
const { data } = await sendApiQuery({
      query: fetchSomethingGql,
      variables: { ... }
});
```

**Comment by YanivSilberman** [comment]
After re-reading that, I'm realizing how unclear I am. I apologize.

Error in content script
```ts
// background
apiQueryStream.subscribe(async ([{ query, variables, options }, _, sendResponse]) => {
    const response = await api.query({
      query,
      variables,
      ...options
    });

    sendResponse(response);
 });

// content 
const { data } = await sendApiQuery({
      query: fetchSomethingGql,
      variables: { ... }
});
```

No problem
```ts
// background
apiQueryStream.subscribe(async ([{ query, variables, options }, _, sendResponse]) => {
    sendResponse({ data: true });
 });

// content 
const { data } = await sendApiQuery({
      query: fetchSomethingGql,
      variables: { ... }
});
```
