### ISSUE TITLE
send message to specific tab

### ISSUE THREAD

**Issue by KnightSlayer** [extend-chrome/messages#6]
### Is your feature request related to a problem? Please describe.

I'd like to send message from background/popup to specific content tab

### Describe the solution you'd like

I'd like `send` method can handle `option.tabId`

### Describe alternatives you've considered

Or another method send*ToContent(tab.id, payload, options)

**Comment by jacksteamdev** [comment]
@KnightSlayer @eabgaryanKandji We need to add this to the documentation, but you can send messages to a tab using the options argument:

```javascript
// background.js
import { messages } from '@extend-chrome/messages'

messages
  .send(
    // Message
    { greeting: 'hello from background' },
    // Options
    { tabId: tab.id },
  )
```

The same options object can be used with the `sendMessage` function returned from `getMessage`.

**Comment by jacksteamdev** [comment]
You can also send a message to a specific frame in a tab using `frameId`
